travis:
  secure:
    BINSTAR_TOKEN: nfXYQ8f5dRL9GTvDJZdL7uav6P1xgRECoqT5MlC54LuWqZYsj3jksgD8SJmOcAa6mNc5k6DgOX/LlnHZ4sx400xolUL5Jh6MsloKdhsVJCLZka9z+N0saiGKww5LHf67XfkHVS8ctp/frCAeIZtivzNPxGqHRLTiR7MxkbUOOSoVo+ix3KMbuXzuTYI5p+MCBjS9MbnJqDj0Ksy7kOumaqr/GenSMtSUVgNhLe4ID+4IlgjyGxfMt3zSX3bcjH0lXjMYEPK/qi419/Jq2Qb5B4KmLMQzWPF+y0a0kl8pxb0Oy9lSuYn2pF4ppq2nmVt0s/TsMaFfj6e54vBV5MuSO1G7mNpMZ6tfWWrJ+pozLnxwPyP0g4zpZbpkxv1nsx13li9z/Vx+0r+YRBFw4Mw045sAU3FvZKJOL85MZ9NCSHotaBuh6i1eMHPOGokpzOh3CR0XN8wZplTqUhA10laGcRzEWRnBt9FLOJ+zwxE5SlQk/7V356Wg1KLCtgQ3SV5EzNjGZret6tLmYuLBRECX8nGsxCRaqsSm/fcG4NPHtxczhquGlu5QGzpR+EWHLjg21sN5HABGnUSGrc/ynewjN/jtB30ofgXzsDNz8ZwAy7kyvoOno1OvwVxBZ35STa0h4hpneX4XBZMmsIIExBoNYzZbWzhtNBGbo/qahLqOMTc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
