travis:
  secure:
    BINSTAR_TOKEN: nqg42WUEO+bG0+03yON6Xq80v5GZkd44B1w5a1Qu0xI+x/SlndXRWfOcYLEO7CVkSTI4SYZUr20TClHY/X+BFro+JrLY2ZYxCSyHZ8o249AGJJVvH7rdGBeAU54Xjgmwil080TgJWKgueaNDLt/IKJYSgc7KuLit3NIHLie+e1RIx1dRuV6DP8oUQhgkPf9TOhE4xGKf23w+kcahnD60sde4KJh6ejrku5Te0qBv0rIHxpV2zMnjniYPclOrOk8kQhWsYtw06tla3GgHxRP0+Tkgu+nnnM3VKrlCDYIojP7gLeCcUEdtMdJBAVqffWANXU4Bol9IOR9rTfbjXnuaC9rOyLCo9O0X7AJgkHTVD5lI9+/mgDpEbFvgrkuxNAVkmk1ERK12cG/bwUym+owlQC2R9obid7KOxcmbqU4Tzat3EMwkXFQn1lA1Y2v1Pgln/csPKTsmgM7wCn4pDfFLvlCUNgAnM6mz5GlSH+DbOQT8woFAbpSq4ZTE5n/anuIRcjEY+Vlx9CASCn2EpbCPuS62DWR42vOkOpEw8smV9v6EOWu5m8cD2F1gZYel1bAb//4Rm+sY3Fr8ssUEbfFpRE800jL4EdtJEIu2zvku1NQZtNZeSFnX+XRzjJLHKueK2XS1R1HtmUHzxDud96iOq5VriwJ2DMmszI24Bm2ZmZE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
